### ISSUE TITLE
Accessing the dynamics

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimhub/nextsimdg#109]
My current understanding of what we need to do/answer to be able to use the dynamics in neXtSIM_DG.

- Merge the dynamics branch with develop and/or main
- A Module for accessing the dynamics (or is the dynamics fixed apart from the choice of rheology?)
- Configuration to read/assign dynamics constants
- Module accessed from within the dynamics to allow run time configuration of the rheology
   - What is the interface from the advection to the rheology?
- Should the dynamics Module be a ModelComponent to directly(ish) access the model data?
   - Probably!
- Refinement of ModelArray to include DG components where necessary
- Are the U/V ModelArray::Types absolutely never needed with DG? (no B/C/D/E grids or equivalent structures)

**Comment by pminak** [comment]
Dynamics work with 2 types of Arrays: 
DG vector of size (mesh.nx*mesh.ny) x degrees of freedom in cell
CG vector of size: CGdegree * mesh.nx + 1) * (CGdegree * mesh.ny + 1) x 1

**Comment by einola** [comment]
Some comments after the meeting in Grenoble:

- @winzerle (that's Thomas, right?) and @pminak will extract a call for a single (long) time step from their current implementation for @timspainNERSC to call from his code
- @timspainNERSC will investigate the use of Eigen arrays and matrixes further
- There will only be one DG implementation - but we should allow for implementations of different dynamics (e.g. Lagrangian).
- Dynamics should be a ModelComponent with direct access to velocities.
- @athelaf will continue to be responsible for MPI parallelisation

Key use cases:
- Simple tests
- Stand-alone regional setups. Size from 100k to 1M elements
- Global coupled model at relatively low resolution (probably 1/2 degree): Number of elements to come
- Extremely high-resolution regional setup (stand-alone). Max 500 m resolution: Number of elements to come

**Comment by timspainNERSC** [comment]
>     * Dynamics should be a ModelComponent with direct access to velocities.

Dynamics should be a ModelComponent which holds the ModelArrays for velocities, concentration, thickness, stress and damage.
The ModelComponent data sharing should provide access to all these arrays (add them to ProtectedArray).

**Comment by timspainNERSC** [comment]
My current thoughts on how to connect the dynamics to the rest of the model.

- The intention is for a single binary to be able to handle any size grid. There should be a way of setting any grid parameters for the dynamics early in the model run.
  - But not any DG/CG degree. That is probably going to be a compile time setting.
- A way of getting the model data from the restart file to the dynamics and back out. Either ModelState needs to be able to cope with fields with DG components, or another more specialized method created.
- A decision on what data is held where and what the sharing mechanism is.
  - My present thinking is that the dynamics hold the full DG/CG versions of the dynamics fields, and any tracer field that needs to be advected. The physics hold a *copy* of the mean component only. This data is copied back and forth every physics timestep.

Feedback on the last point would be appreciated.

**Comment by winzerle** [comment]
* Data handling seems reasonable. dynamics stores all that it really needs with higher oder and we provide access to the mean. 
* Within dynamics the templates could be encapsulated as done in the application/benchmark_mehlmann_sasip_mevp.cpp then all template arguments are in one place, which would be the interface between dynamics and physics. 
*

**Comment by einola** [comment]
Yes, this seems reasonable. The only question is if the copying (in point 3) will be expensive. I suggest that we implement it like this and then profile the code. If copying is expensive, then we'll have to re-think.

**Comment by einola** [comment]
> To get an idea: the high order advection of one tracer is about 1% (more or less) of the momentum iteration. And copying such a vector is even far less.

That's very useful information! And an interesting result too. So now I'm not worried about the copying :)

**Comment by timspainNERSC** [comment]
During the meeting on 12th September, @draenog pointed out that another possible solution is to have the data structure in the physics part of the model reference/slice the full DG arrays in the dynamics such that they only ever see the finite element DG component. This would be an alternative to the method of copying data back and forth between physics and dynamics.

**Comment by einola** [comment]
I think this one should remain in milestone 1, as almost everything mentioned here is needed for a minimum viable model that can run the dynamics within the complete framework and not as a separate application.

**Comment by timspainNERSC** [comment]
> I think this one should remain in milestone 1, as almost everything mentioned here is needed for a minimum viable model that can run the dynamics within the complete framework and not as a separate application.

Are you still sure about this? It will require pulling a lot of what is currently flagged as milestone 2 into milestone 1. At a minimum merging PRs #250 #389 

But possibly that is all.

**Comment by einola** [comment]
It's two!

**Comment by timspainNERSC** [comment]
> > I think this one should remain in milestone 1, as almost everything mentioned here is needed for a minimum viable model that can run the dynamics within the complete framework and not as a separate application.
> 
> Are you still sure about this? It will require pulling a lot of what is currently flagged as milestone 2 into milestone 1. At a minimum merging PRs #250 #389
> 
> But possibly that is all.

PRs #250 and #389 have been merged.
