### ISSUE TITLE
Output restart files at points other than the end of the run

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimhub/nextsimdg#239]
Being able to restart from the end of a run is the bare minimum functionality. The user should be able to specify a repeat time for the creation of restart files. Also, it might be necessary for the model to be able to receive a signal that it should output a restart file at some point, this being my current understand of how it will work coupled to NorESM.

**Comment by dorchard** [comment]
This looks good but I was wondering a bit about the split of having `PrognosticData::writeRestartFile` in `PDWriter.cpp` rather than in `PrognosticData.cpp`?

**Comment by timspainNERSC** [comment]
So that the tests that use the PrognosticData class can use an alternative implementation which doesn't require linking all of the IO classes and the netCDF library.

See [PrognosticData_test](https://github.com/nextsimdg/nextsimdg/blob/1dff2062d9fe9eba2c1192b61fddbe9834d9eb07/core/test/PrognosticData_test.cpp#L26) as an example.

**Comment by dorchard** [comment]
Ah okay- I see. Thanks!

**Comment by timspainNERSC** [comment]
Merged.
