### ISSUE TITLE
Communication between Dynamics and Physics

### ISSUE THREAD

**Issue by pminak** [nextsimhub/nextsimdg#259]
List of functionalities:
- Dynamics can be restarted from file (we save all DG/CG components)
- Dynamics shares data with Physis on DG0 component (average value on element).
- Dynamics gets DG0 data from Physics. We accept NaNs on the land (TODO: check interpolation).

**Comment by timspainNERSC** [comment]
Moving to milestone 2 Functional tests, as that is where it ended up.

**Comment by timspainNERSC** [comment]
Closing due to the merging of PR #389
