### ISSUE TITLE
XIOS: Add Handler/Interface Class & Calendar Management (and include in CMake)

### ISSUE THREAD

**Issue by a-smith-github** [nextsimhub/nextsimdg#293]
This is a sub-feature of issue #218 tracking the addition of a new XIOS class that interfaces with the XIOS library and server process. The first step is to initialise the calendar and advance time, this is the pilot issue that navigates interfacing with undocumented XIOS library methods.

See [xios-cpp-toy](https://github.com/nextsimhub/xios_cpp_toy/blob/master/inc/my_xios.hpp) repository for more information

This provides the foundation for adding grid & axis data tracked in issue #292 (see parent issue #218) 

This will require MPI initialisation - either via new feature or a temporary localised implementation. 

For the XIOS Integration, see the [design spec](https://github.com/nextsimdg/nextsimdg/wiki/XIOS-Integration) or the [master pull request](https://github.com/nextsimhub/nextsimdg/pull/265)

**Comment by jwallwork23** [comment]
Closed by #496.
