### ISSUE TITLE
Fix type qualifier warning during compile (ModelArray.hpp #includes)

### ISSUE THREAD

**Issue by a-smith-github** [nextsimhub/nextsimdg#325]
When compiling any target that depends on a source which includes ModelArray.hpp when using compiler 'mpiicpc' you get a warning. 

---
Syndrome:

[ 22%] Building CXX object CMakeFiles/nextsim.dir/core/src/DevGridIO.cpp.o
In file included from /home/jbloggs/nextsim/xios_write/core/src/include/ModelState.hpp(11),
                 from /home/jbloggs/nextsim/xios_write/core/src/include/IDevGridIO.hpp(12),
                 from /home/jbloggs/nextsim/xios_write/core/src/include/DevGridIO.hpp(11),
                 from /home/jbloggs/nextsim/xios_write/core/src/DevGridIO.cpp(8):
/home/jbloggs/nextsim/xios_write/core/src/include/ModelArray.hpp(241): warning #858: type qualifier on return type is meaningless
      const Type getType() const { return type; }
      ^

---
Reproduction Steps:

Repeat install steps but replace the cmake line with
cmake . -DCMAKE_CXX_COMPILER="mpiicpc"

make step should trigger the warnings

---
Severity & Frequency:

Low impact. UX and only at compile (but for many many files). Have not investigated compile speed impact. Remove bug label at triage if inappropriate (readme isn't specific).

**Comment by timspainNERSC** [comment]
Either `Type` or `const Type&` would work. Is either preferred?
