### ISSUE TITLE
ERA polar winds are bad

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimhub/nextsimdg#368]
The base ERA5 data files have a polar row in the wind data that is set to a constant for all longitudes for each component. This is clearly incorrect. A consistent value of the wind in a long-lat grid can be represented as a pair of sinusoidal functions in longitude, in quadrature for each component. The polar adjacent row shows almost exactly this behaviour as the variation in the true wind is not that great over the 25 km radius circle this row represents.

When interpolating the wind vector components to the model grid, this wind vector interpolation makes the pole very obvious as a point inconsistent with the rest of the wind field. The ERA5 pre-processing python script should be altered so that polar point is interpolated correctly to give a smooth wind field.

**Comment by einola** [comment]
@brodeau apparently simply ignores this polar row in his scripts. This is a sensible and simple approach.
