### ISSUE TITLE
The BBM rheology exists, but is not usable

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimhub/nextsimdg#378]
Within the dynamics of the model, the BBM rheology exists (`dynamics/src/include/bbm.hpp`). It is not currently usable as the dynamics are hard-coded to use MEVP. Implement an additional class derived from `IDynamics` that which uses the BBM update function and provides all the other data and configuration required to enable this.

**Comment by timspainNERSC** [comment]
Notes from a morning's investigation:
Three functions exist in `cgParametricMomentum.cpp`:
* `mEVPStep`
* `MEBStep`
* `BBMStep`
This suggests that the switching can take place with the `DynamicsKernel` class.

There is a lot of overlap between the three functions, and they would fir quite well into an object oriented framework.

The parameter sets, stored in the classes `VPParameters` and `MEBParameters` are constant per-model run and are also amenable to being turned into a class hierarchy (of two).

The function `prepareIteration` exists in versions with and without a damage argument. These would probably be better described as mEVP and non-mEVP versions, as the contained functionality is different, depending on whether the damage argument is passed.

**Comment by timspainNERSC** [comment]
The MEB and BBM rheologies should be merged as far as possible, since they are identical with the exception of a single term, P tilde.

If the refactoring can be performed in such a way to abstract the mesh dependent operation from the rest, that would be an advantage for including other meshes. This would be anything in the code that performs a horizontal derivative. This is likely limited to the advection and the calculation of the rate of strain tensor from the horizontal velocity gradients. The rest of the rheology is performed on a per-point basis and could (likely) be the same between a structured grid and an unstructured mesh.

Is there any scope to support semi-implicit solution of the momentum equation? Currently all schemes are explicitly solved.

**Comment by einola** [comment]
We abandoned the semi-implicit approach, as it's too costly for a large-scale model. Re-introducing it would be a significant development, and I don't have any good ideas on how it can be done cost-efficiently.

**Comment by timspainNERSC** [comment]
Current design as of end January 2024 (potentially subject to much change):

The dynamics are called from a module that is referenced in `PrognosticData`, with interface type `IDynamics`. This will have four implementation classes, corresponding to the three current rheologies plus no dynamics:

- `DummyDynamics`
- `MEVPDynamics`
- `MEBDynamics`
- `BBMDynamics`.

These classes exist to transfer the `ModelArray` data into and out of the classes in the dynamics subdirectory described below and to control the timestepping in a manner consistent with the other parts of the model. The `ModelData` arrays containing the ice velocity are also owned by this class, and shared using the `ModelArrayRef` system. These hold only the finite volume/DG0 component of the velocity data.

Within the dynamics subdirectory, there are the dynamics kernels, derived from the `DynamicsKernel` base class. This provides a common interface and infrastructural functions for the current and future rheologies. In addition, there is `DummyDynamicsKernel` which is not a derived class, but acts in the same way for the dummy dynamics. The dynamics kernels derived from `DynamicsKernel` again reflect the three current rheologies:

- `MEVPDynamicsKernel`
- `MEBDynamicsKernel`
- `BBMDynamicsKernel`

The dynamics kernel classes use momentum solver to isolate the dependency on continuousGalerkin to a easily replaceable class. This is to be implemented by choosing which source file to use to provide the `DynamicsKernel` function implementations. Currently this is `CGDynamicsKernel.cpp`, but other momentum solvers may be included in the model in the future.

*TBC*

**Comment by timspainNERSC** [comment]
Fixed as part of #477.
