### ISSUE TITLE
Decision about extending OpenMP or MPI first

### ISSUE THREAD

**Issue by MarionBWeinzierl** [nextsimhub/nextsimdg#443]
Currently, there are OpenMP directives in the dynamics code, and an MPI implementation is being added to the thermodynamics code in #331 .

The question is now whether to go forward with #120 or with #334 first to achieve a hybrid implementation. 

The former will probably be quicker.

@einola has set the 1.1.2024 as a deadline for a simple MPI implementation which will allow coupling.

**Comment by timspainNERSC** [comment]
> @einola has set the 1.1.2004 as a deadline for a simple MPI implementation which will allow coupling.

For clarity, 1.1.2024, else we are very late!

**Comment by einola** [comment]
If you say that #120 would be quicker, let's do that first.

We know that we need MPI, and having some MPI parallelisation of the dynamics is nice, but we're not entirely sure if hybrid MPI+OpenMP is faster than only MPI.
