### ISSUE TITLE
Tidy up the rheology code

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimhub/nextsimdg#450]
On first looking at the rheology code, it looks like an horrendous mess.
However, I suggest that by a few simple `typedefs`, the code can be made to look more like physics and less like C++.

For example, here is some of the core calculation of the function `StressUpdateHighOrder()` in `BBM.hpp`:
```
            const Eigen::Matrix<double, 1, NGP* NGP> powalphaexpC
                = (d_gauss.array() * expC.array()).pow(params.exponent_relaxation_sigma - 1);
            const Eigen::Matrix<double, 1, NGP* NGP> time_viscous
                = params.undamaged_time_relaxation_sigma * powalphaexpC;

            //! BBM  Computing tildeP according to (Eqn. 7b and Eqn. 8)
            // (Eqn. 8)
            const Eigen::Matrix<double, 1, NGP* NGP> Pmax
                = params.P0 * h_gauss.array().pow(params.exponent_compression_factor) * expC.array();
```

I would argue that adding a `typedef Eigen::Matrix<double, 1, NGP * NGP> GaussVar;` makes the physical equations that are being evaluated much clearer:
```
        // Eqn. 25
        const GaussVar powalphaexpC = (d_gauss.array() * expC.array()).pow(
                params.exponent_relaxation_sigma - 1);
        const GaussVar time_viscous = params.undamaged_time_relaxation_sigma * powalphaexpC;

        //! BBM  Computing tildeP according to (Eqn. 7b and Eqn. 8)
        // (Eqn. 8)
        const GaussVar Pmax = params.P0 * h_gauss.array().pow(params.exponent_compression_factor)
                * expC.array();
```
because the code is no longer dominated by the types and template arguments. To me, even as someone experienced with C++, this is easier to read.

There may be other renamings and rearrangings that are possible to make the code in these functions even clearer.

**Comment by timspainNERSC** [comment]
The variable name `GaussVar` could of course itself be changed to something more accurately descriptive.

**Comment by timspainNERSC** [comment]
I'm especially interested in comments from @winzerle on this.

**Comment by winzerle** [comment]
Using a typedef is no problem and of coarse, will help the readability. This type is always a vector of values in the Gauss points within the element. So GaussVar is ok, or maybe GaussVector. 

In different parts of the code such a vector appears for values in the elements and for values on the edges. Once it is NGP*NGP as template argument, one just NGP.

There is another thing: to avoid linking problems the value of NGP always has to match. I see that this function still locally uses 

#define NGP ( ((DGstress == 8) || (DGstress == 6) ) ? 3 : (DGstress == 3 ? 2 : -1))

I would prefer that we always use

#define GAUSSPOINTS(Q) (( (Q == 8) || (Q==6) ) ? 9 : (Q == 3) ? 4   : (Q==1) ? 1 : -1)
#define GAUSSPOINTS1D(Q) (( (Q == 8) || (Q==6) ) ? 3 : (Q == 3) ? 2  : (Q==1) ? 1 : -1)

from include/NextsimDynamics.hpp 

It could then be

typedef Eigen::Matrix<double, 1, GAUSSPOINTS<DGstress> > GaussVector
typedef Eigen::Matrix<double, 1, GAUSSPOINTS1d<DGstress> > GaussVectorEdge


In cleaning up the code there is just one important issue: we have to avoid using the keyword "auto" with Eigen. This will kill the efficiency.

**Comment by timspainNERSC** [comment]
> we have to avoid using the keyword "auto" with Eigen. This will kill the efficiency.

Good to know!

**Comment by timspainNERSC** [comment]
Tidied up as part of PR #477.
