### ISSUE TITLE
Spherical coordinates for the dynamics

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimhub/nextsimdg#463]
Currently the DG dynamics in nextSIM assume Cartesian coordinates, and any spherical coordinates will be replaced with a 25 km Cartesian grid.

- [x] Check the operation of the dynamics with spherical coordinates.
- [x] Determine within nextSIM-DG if spherical or Cartesian coordinates should be used.

**Comment by timspainNERSC** [comment]
> Check the operation of the dynamics with spherical coordinates.
They're bad. Really bad.

**Comment by winzerle** [comment]
Hi Tim :-) 

Guess we need to discuss this in some detail. I am sure that it will require some work to make it really run in one of your test cases. There are many things to settle such as the system for angles (radians, degrees, etc.). But there will be much more. There are many decisions to be made when going to spherical coordinates and I choice between various options :-) We should zoom :-) 

Also regarding boundary. I am on it and there I have a good idea on how to integrate it.

Thomas


* --------------------------------------------
| Prof. Dr. Thomas Richter
| Numerische Mathematik in den Anwendungen
| Otto-von-Guericke Universität Magdeburg
| numerics.ovgu.de
| +49 391 67-57162  +49 176 615 612 26 (mobil)
