### ISSUE TITLE
Replace dynamics namespaces with classes

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimhub/nextsimdg#467]
(If possible!)

The functions defining the behaviour of the mEVP, MEB and BBM dynamics solvers are grouped using namespaces, rather than classes. Using classes would potentially permit the use of the nextSIM-DG `Module` system to swap dynamics types at run time.

@winzerle and @einola: Is there a reason why these functions are in namespaces, rather than classes?

**Comment by winzerle** [comment]
Hi everyone and happy New Year!

There is no reason at all for it. First it was just part of the Momentum class and then, this strange solution made the development for Piotr and me easier. But of course, it should be a class.

Thomas


* --------------------------------------------
| Prof. Dr. Thomas Richter
| Numerische Mathematik in den Anwendungen
| Otto-von-Guericke Universität Magdeburg
| numerics.ovgu.de
| +49 391 67-57162  +49 176 615 612 26 (mobil)

**Comment by einola** [comment]
Hi, and Happy New Year!

I agree that there's no other reason than practical expediency during the development. We should, therefore, change it so it uses classes and the ``Module`` system.

**Comment by timspainNERSC** [comment]
The work for this is contained in PR #477

**Comment by timspainNERSC** [comment]
Fixed as part of PR #477.
