### ISSUE TITLE
Model crashes on thermodynamics test

### ISSUE THREAD

**Issue by einola** [nextsimhub/nextsimdg#470]
Running the thermodynamics test is not successful with develop. The model crashes with a sigsev (11).

This seems to be a general problem that also occurs with the other config files.

The investigation is ongoing.

**Comment by einola** [comment]
The debugger points to line 58 of [Logged.hpp](https://github.com/nextsimhub/nextsimdg/blob/879c54392b1912e39b51f6d2adf91bc040adcaf4/core/src/Logged.cpp#L58)

**Comment by MarionBWeinzierl** [comment]
I ran this branch as well as the develop branch for comparison. They both run through without problems, generating the relevant files. (on Ubuntu 23.04)

**Comment by timspainNERSC** [comment]
Using both `develop` and `issue470_crash` I get a SEGFAULT displayed as 
```
Segmentation fault: 11
```
This occurs at the end of the run (after the end of `~Model()`), with the diagnostic and restart files having been successfully written.

MacOS 13.6.3
AppleClang 15.0.0.15000100

**Comment by einola** [comment]
With the current develop on an Intel Mac, doing a fresh build, make says

```
Monaco:build einola$ cmake ..
-- The C compiler identification is AppleClang 15.0.0.15000100
-- The CXX compiler identification is AppleClang 15.0.0.15000100
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.29.2") 
-- Checking for one of the modules 'netcdf-cxx4'
-- Found OpenMP_C: -Xclang -fopenmp (found version "5.0") 
-- Found OpenMP_CXX: -Xclang -fopenmp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found Boost: /opt/local/include (found version "1.76.0") found components: program_options log date_time log_setup filesystem thread regex chrono atomic 
-- Found PythonInterp: /opt/local/bin/python (found version "3.11.7") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/einola/CLionProjects/nextsimdg/build
```
 and I get a segfault and no `.log` or `.nc` file created/updated.

```
Monaco:run einola$ ./nextsim --config-file config_column.cfg 
Segmentation fault: 11
```

Switching to `issue470_crash` the model runs to the end and produces the expected files (with the expected contents).

```
Monaco:run einola$ ./nextsim --config-file config_column.cfg 
Monaco:run einola$ echo $?
0
```
