### ISSUE TITLE
Incorrect duration

### ISSUE THREAD

**Issue by einola** [nextsimhub/nextsimdg#473]
The thermodynamics test crashes with the message

```libc++abi: terminating due to uncaught exception of type std::invalid_argument: The duration should be an ISO 8601 duration (P…) or a number of seconds. Got: ```

This seems to be related to PR #294, as rolling the model back to 55548256fa2f9bd1d4410e69c80f5d8be8865314 (before that PR) from 1eed3eee62025f190a4994286452245188e01e2d (current develop) the model runs fine.

The debugger was not very helpful, but I'm still investigating.

**Comment by einola** [comment]
I think there's something wrong with how `string` and `istream` are handled in `Time.cpp`. I am still figuring out exactly how to fix it.

**Comment by timspainNERSC** [comment]
The problem is with parsing an empty string, which is what the (absent) configuration defaults to.
