### ISSUE TITLE
Implement damage healing

### ISSUE THREAD

**Issue by einola** [nextsimhub/nextsimdg#529]
We still don't heal damage in BBM, which is needed for longer runs. There are two options for healing:
 - Constant healing time scale
 - Temperature-dependent healing time scale

The temperature dependence in Olason et al. (2022) and Rampal et al. (2016) is very ad hoc but the best we have so far. It should be implemented in the thermodynamics routine. The problem is how to have healing independent of the chosen thermodynamics module - we don't want to re-implement the same thing repeatedly.

**Comment by timspainNERSC** [comment]
The way to avoid repeated re-implementation is to use the Module system.

The call tree from `PrognosticData::update()` into the thermodynamics is:
- `PrognosticData::update()`
  - `IceGrowth::update()` note that this is not a module!
    - `IIceThermodynamics::update()` the ice thermodynamics module
    - `newIceFormation(i)` cooling flux -> increased concentration
    - `lateralIceSpread(i)` 

I would suggest that an additional call could be made to the new `IDamageHealing::update()` within `IceGrowth::update()`. Unless the damage healing _has_ to be embedded inside `ThermoWinton::update()`/`ThermoIce0::update()` for a reason I am not currently seeing.

**Comment by timspainNERSC** [comment]
Fixed by merging PR #607 
(Once again, I feel this should happen more automatically).

**Comment by einola** [comment]
I should have closed it manually, of course :/

It should close automatically because the PR commit message contains the magic string "Fixes #ISSUE-NUMBER". See https://github.com/gitbucket/gitbucket/wiki/How-to-Close-Reference-issues-and-pull-request

I'll open a separate issue.
