### ISSUE TITLE
add domain_decomp tool to CI and docker image 

### ISSUE THREAD

**Issue by TomMelt** [nextsimhub/nextsimdg#541]
Currently any MPI test that calls `RectGridIO`/`ParaGridIO` requires a metadata file generated by `domain_decomp` tool.

We should look to add `domain_decomp` to the build dependencies in the long term and the docker image.

Then it could be added to CMake in a similar way to `python` which is used to generate test data (`.nc` files)

**Comment by jwallwork23** [comment]
I decided to add it to the Docker image as part of #647 since that PR already modifies it.

I'll make use of decomp in the nextSIM-DG test suite in a follow-up PR.

**Comment by jwallwork23** [comment]
We determined that the second part of this issue request is actually an impossible task. The partition files are set up to unevenly divide a domain with no land, which `domain_decomp` will never do.
