### ISSUE TITLE
Run Dynamics Tests in CI

### ISSUE THREAD

**Issue by MarionBWeinzierl** [nextsimhub/nextsimdg#549]
Take the tests from https://github.com/nextsimhub/nextsimdg/tree/issue188/dynamics/tests and implement them in the CI pipeline in Github Actions. This will enable to monitor that changes made in the parallelisation (#120, #448, #495 etc) do not change the behaviour of the dynamics code.

**Comment by MarionBWeinzierl** [comment]
Looking through the git history, the tests were merged into develop, but later deleted in commit https://github.com/nextsimhub/nextsimdg/commit/b1a110595cc72a64dc5bcc87fdf1e69fbfa73cdd

**Comment by TomMelt** [comment]
fixed by #556
