### ISSUE TITLE
Check (and fix) clang-format defaults to avoid version issue

### ISSUE THREAD

**Issue by MarionBWeinzierl** [nextsimhub/nextsimdg#563]
When working on #556 , CI threw an error when using a newer version of clang-format. The local version used was `Ubuntu clang-format version 18.1.3` (on Ubunut 24.04). I worked in the Docker containers, using `Ubuntu clang-format version 14.0.0-1ubuntu1.1`.

It could be a problem with some of the clang-format styles going to `default`, rather than being explicitly defined -- this would cause a problem if the defaults change.

It has to be checked whether this is the case, or whether there were other changes in the clang-format version which could cause this problem.

**Comment by TomMelt** [comment]
I will look and see if it's possible to freeze defaults to match github runner version

**Comment by einola** [comment]
I looked at the .clang-format file. The only "default" value is for "SpaceAroundPointerQualifiers ". But this means "Don't ensure spaces around pointer qualifiers and use PointerAlignment instead" [(see the clang-format docs)](https://clang.llvm.org/docs/ClangFormatStyleOptions.html), so it has a very well-documented behaviour. It's not a "default" value that can change.

We're running clang version 14 on the CI, but the latest stable version is 19. I haven't checked thoroughly, but there is a behaviour where multiplication within a template argument is formatted differently in version 14 compared to later versions. This is the only difference I've seen, and it's consistent in versions 16 and 18 (the ones I've tried). Maybe the old behaviour was simply a bug.

Can we update clang on the CI and reformat the code? It's not reasonable to stick with an outdated version of clang-format.

I suppose the solution is to upgrade the OS in the ``clang_format.yml`` workflow. Do you see any problems changing from 22.04 to 24.04 (LTS)?
