### ISSUE TITLE
Refactor the two dynamics advection tests with doctest

### ISSUE THREAD

**Issue by MarionBWeinzierl** [nextsimhub/nextsimdg#587]
In #556, I added minimal doctest functionality to the advection tests in dynamics. A proper refactor to fully comply with the doctest scheme elsewhere should to conducted for those two files.

**Comment by TomMelt** [comment]
currently the original dynamics test is essentially wrapped by `doctest`, but it still uses a rudimentary comparison under-the-hood. 
https://github.com/nextsimhub/nextsimdg/blob/e3a2d84acfbac871ada17eb0cd44fff561cf362c/dynamics/test/Advection_test.cpp#L264-L271

This could be converted to use [`doctest::Approx`](https://github.com/doctest/doctest/blob/master/doc/markdown/assertions.md#floating-point-comparisons) for the `doctest` version of floating point comparison
