### ISSUE TITLE
ConfigOutput only generates output if ``start`` option is set

### ISSUE THREAD

**Issue by einola** [nextsimhub/nextsimdg#599]
The ``ConfigOutput`` module will not generate any output if the ``ConfigOutput.start`` option is not set. The expectation is that not setting ``ConfigOutput.start`` is equivalent to setting it to the model start (``Model.start``).

To reproduce, pick a favourite config file (e.g. ``config_column.cfg``) and remove the ``ConfigOutput.start`` option.

**Comment by timspainNERSC** [comment]
The default value of the start time should be the model start time. I'm sure I wrote code to do this in the past. The help text even says that `model.start` is the default value. I'm not sure what happened to that code.
```
    map[pfx] = {
        …
        { startKey, ConfigType::STRING, {}, "model.start", "",
            "Date at which to start outputting data." },
        …
    };
```
