### ISSUE TITLE
Remnant Module dirs when switching branches

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimhub/nextsimdg#608]
If a branch introduces a new Module, switching away from it will leave the Module subdirectory behind, containing the generated `module.cpp` file. The Module generation code should ignore or delete such directories. The telltale signature is a Module directory containing only a `module.cpp` file.

**Comment by einola** [comment]
Yes! A very minor thing that's super annoying :D

**Comment by timspainNERSC** [comment]
I'm about to create a new module, and I don't want this to bite me when switching branches, so I will fix this now.
