### ISSUE TITLE
clang format - is this expected behaviour

### ISSUE THREAD

**Issue by TomMelt** [nextsimhub/nextsimdg#616]
@timspainNERSC, quick question. I am in the process of rebasing #556 and I realised some formatting discrepancies between two clang-formatted versions of `dynamics/src/include/Tools.hpp`. The following line feels like something that should be tidied up by the formatter but it isn't.

https://github.com/nextsimhub/nextsimdg/blob/0fb6d41c98695e0d6709719d64b6fa7578b3b592/dynamics/src/include/Tools.hpp#L101

Is this deliberate / expected behaviour. I thought it would at least split it over multiple lines.

When I run `clang-format -i dynamics/src/include/Tools.hpp` this line does not change. Equally, if I manually split it to something like the following, it will remain untouched by the formatter:

```cpp
                SHEAR.row(i) = ParametricTools::massMatrix<S2A(DGs)>(smesh, i).inverse()
                    * (PSI<S2A(DGs), NGP>
                        * (((e11_gauss.array() - e22_gauss.array()).square()
                               + 4.0 * e12_gauss.array().square() + 1.e-20)
                                .sqrt()
                                .log10()
                            * ParametricTools::J<NGP>(smesh, i).array() * GAUSSWEIGHTS<NGP>.array())
                              .matrix()
                              .transpose());
```

**Comment by timspainNERSC** [comment]
This is Thomas' code. As far as I am concerned 'here be Dragons' and anything that passes CI, goes.

**Comment by TomMelt** [comment]
That's ok. I understand you didn't write it. Just curious if we want `clang-formatter` to be stricter. I would have thought that it would split really long lines into something more readable. But it's not a problem :ok_hand:
