### ISSUE TITLE
Base XIOS tests off `ModelArray` definitions

### ISSUE THREAD

**Issue by jwallwork23** [nextsimhub/nextsimdg#633]
Before fully addressing #552, we should rework the XIOS tests so that they start from `ModelArray` definitions and deduce the relevant XIOS concepts from these.

**Comment by joewallwork** [comment]
In hindsight, I don't think these needs to be done in all the XIOS tests. For the ones that are purely concerned with the `Xios` handler class, we can just test the methods directly.

Already addressed in #728 for the read/write cases, so can close here.
